# Day-3
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <h1>Challenges In Machine Learning</h1>
  <ol>
    <li>
      <h3>Data Collection</h3>
      <ul>
        <li>Mostly we will collect data from two sources for real world projects. First one is from API (like Flickr) and second one is using web scraping (like Google).</li>
      </ul>
    </li>
    <li>Insufficient data/labeled data</li>
    <li>Non Representative Data</li>
    <li>Poor Quality of data</li>
    <li>Irrelevant features</li>
    <li>Overfitting</li>
    <li>Underfitting</li>
    <li>Software Integration</li>
    <li>Offline Learning/Deployment</li>
    <ul>
      <li>To fit new data to the previous ML model, the offline learning and deployment method will be quite expensive.</li>
    </ul>
    <li>Cost Involved</li>
    <ul>
      <li>Hidden cost of ML model deployment will be high.</li>
    </ul>
  </ol>

  <h1>Application of Machine Learning</h1>
  <h3>B2C</h3>
  <ul>
    <li>Facebook Friends Recommendation</li>
    <li>Product Recommendation</li>
    <li>Video Recommendation</li>
  </ul>
  <h3>B2B</h3>
  <ul>
    <li>Retail</li>
    <li>Banking and Finance</li>
    <li>Transport (Logistic Service)</li>
    <li>Manufacturing-Tesla (Robotic Arm)</li>
    <li>Consumer Internet- Twitter (Sentimental Analysis)</li>
  </ul>
  <p>
    At first, Twitter was not really earning money from it, so they decided to create sentimental analysis of hashtags topics and sell them to people who were really into the share market, and so on. Let's take an example of who is going to be the next PM of Nepal, so Twitter will collect the data related to #election2029 and analyze that tweet and sell it to the necessary persona, and that persona will return money to Twitter. This is just an example of sentimental analysis implemented by Twitter.
  </p>

  <h1>Machine Learning Development Life Cycle (MLDLC)</h1>
  <ol>
    <li>
      <h3>Frame the problem</h3>
      <ul>
        <li>Identify the problem.</li>
      </ul>
    </li>
    <li>
      <h3>Gather Data</h3>
      <ul>
        <li>Csv</li>
        <li>API</li>
        <li>Web Scraping</li>
        <li>Database</li>
        <li>Spark Clusters</li>
      </ul>
    </li>
    <li>
      <h3>Data Preprocessing</h3>
      <ul>
        <li>Remove duplicates</li>
        <li>Remove missing values</li>
        <li>Remove outliers</li>
        <li>Standardization (Scaling)</li>
      </ul>
    </li>
    <li>
      <h3>Exploratory data analysis</h3>
      <ul>
        <li>Visualization of Data</li>
        <li>Univariate/Bivariate
</li>
        <li>Outlier detection</li>
        <li>Data Balance</li>
      </ul>
    </li>
    <li>
      <h3>Feature engineering and selection</h3>
    </li>
    <li>
      <h3>Model Training, Evaluation, and Selection</h3>
      <ul>
        <li>In this process, we will train all possible algorithms for that particular dataset and select which algorithm is best for the dataset. We can also say that we will evaluate all algorithm models.</li>
        <li>Ensemble learnings: We will use more algorithms, or we will add multiple ML algorithms and make new powerful methods or algorithms that include</li>
        <ul>
          <li>Hyperparameter Tuning</li>
          <li>Bagging, boosting, stacking, buckets of models, voting [Wikipedia.org]</li>
        </ul>
      </ul>
    </li>
    <li>
      <h3>Model deployment</h3>
    </li>
    <li>
      <h3>Testing</h3>
      <ul>
        <li>We will give new updates to loyal customers, and that loyal customer will give you feedback about ML models.</li>
        <li>A/B testing is used to measure how your model is actually doing.</li>
      </ul>
    </li>
    <li>
      <h3>Optimize</h3>
      <ul>
        <li>Model Backup</li>
        <li>Data Backup</li>
        <li>Rollback Automation</li>
        <li>Load balancing</li>
        <li>Model Retrain: [Rotting]: It is a concept of a model not doing well after some days, months, and so on.</li>
      </ul>
    </li>
  </ol>
  <h1>Data Engineer Vs Data Analyst Vs Data Scientist Vs ML Engineer</h1>
  <ol>
    <li>Data Engineer: In simpler terms, its role is to scrape the data, and we can also say that they will do the data collection process.</li>
    <li>Data Analyst: Their main role is to do data preprocess and visualize the data.</li>
    <li>Data Scientist: The main role of a data scientist is to determine what we can make from using the above data which is provided by a data engineer and data analyst.</li>
    <li>ML Engineer: The main role of ML engineer is to deploy the ML model to a product-ready environment and monitor and maintain the deployed model.</li>
  </ol>
  <h1>Tensors and its in-depth knowledge</h1>
  <ul>
    <li>Tensors are the data structure.</li>
    <li>Or we can also say that it is the container of numbers where we will store the numerical data only (most of the time).</li>
    <li>Vector-Matrix=Tensors</li>
    <li>
      <h3>0-Dimensional</h3>
      <ul>
        <li>np.array(4)</li>
        <li>Output: array(4) # Single Number/scalar.</li>
      </ul>
    </li>
    <li>
      <h3>1-Dimensional</h3>
      <ul>
        <li>np.array([1,2,3,4])</li>
        <li>It is 1-dimensional data /4 vector/1d array</li>
      </ul>
    </li>
    <li>
      <h3>2-Dimensional</h3>
      <ul>
        <li>np.array([[1,2,3],[4,5,6],[7,8,9]])</li>
<li>It is 2D tensors or we can also say that it is the collection of vectors.</li>
</ul>
</li>
<li>
<h3>3-dimensional</h3>
<ul>
<li>Example of 3D is a single RGB image</li>
<li>Dimensions=(height of image, width of image, color channel)</li>
</ul>
</li>
<li>
<h3>4-Dimensional</h3>
<ul>
<li>Multiple images like 20 images</li>
<li>Dimensions=(total image, height, width, channel)</li>
</ul>
</li>
<li>
<h3>5-Dimensional</h3>
<ul>
<li>Video of 60 sec</li>
<li>Dimensions=(times, frames, height, width, channels)</li>
<li>Shape(60 sec, 30 fps, 420, 720, 3)</li>
</ul>
</li>

  </ul>
</body>
</html>

# Tensors 

- Tensors is nothing but it is data structure
- It is a conatainer for numbers[99% numbers]

##### We can also say that vector-Metrix to Tensors
>-  0-Dimensionsional      = Scaler
>- List of numbers         = Vector
>- 2d                      =Matrix
>- 3d-4d                   =Tensors

In [2]:
import numpy as np


- Axis=Dimension
- ndim=to check the dimension
- & 
- Number of Axis =Rank
- Rank=Dimension

### 0-d Tensors

In [3]:
zero_d=np.array(4)
zero_d
# We can say thisis 0d tensors

array(4)

In [4]:
zero_d.ndim # this is used to check the dimension of the array or tensors

0

### 1-D Tensors/Vector

In [5]:
one_d=np.array([1,2,3,4])
one_d

array([1, 2, 3, 4])

In [6]:
one_d.ndim # to check the dimension of tensors


1

### 2-d Tensors

In [7]:
two_d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
two_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3-d Tensors
- Image Height, Image Width ,Color Channel

In [ ]:
three_d = np.array([[[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]],
                    
                    [[10, 11, 12],
                     [13, 14, 15],
                     [16, 17, 18]],
                    
                    [[19, 20, 21],
                     [22, 23, 24],
                     [25, 26, 27]]])

print(three_d)


### 4-d Tensors
- Collection of Images

In [ ]:
four_d = np.array([[[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],
                     
                     [[10, 11, 12],
                      [13, 14, 15],
                      [16, 17, 18]],
                     
                     [[19, 20, 21],
                      [22, 23, 24],
                      [25, 26, 27]]],

                    [[[28, 29, 30],
                      [31, 32, 33],
                      [34, 35, 36]],
                     
                     [[37, 38, 39],
                      [40, 41, 42],
                      [43, 44, 45]],
                     
                     [[46, 47, 48],
                      [49, 50, 51],
                      [52, 53, 54]]]])

print(four_d)


### 5-d Tensors
- Video(60 Sec,30 Fps,480 height,720 width,3 colors channel(RGB)

In [11]:
five_d = np.array([[[[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]],
                      
                      [[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]],
                      
                      [[19, 20, 21],
                       [22, 23, 24],
                       [25, 26, 27]]],
                     
                     [[[28, 29, 30],
                       [31, 32, 33],
                       [34, 35, 36]],
                      
                      [[37, 38, 39],
                       [40, 41, 42],
                       [43, 44, 45]],
                      
                      [[46, 47, 48],
                       [49, 50, 51],
                       [52, 53, 54]]]],
                   
                    
                    [[[[55, 56, 57],
                       [58, 59, 60],
                       [61, 62, 63]],
                      
                      [[64, 65, 66],
                       [67, 68, 69],
                       [70, 71, 72]],
                      
                      [[73, 74, 75],
                       [76, 77, 78],
                       [79, 80, 81]]],
                     
                     [[[82, 83, 84],
                       [85, 86, 87],
                       [88, 89, 90]],
                      
                      [[91, 92, 93],
                       [94, 95, 96],
                       [97, 98, 99]],
                      
                      [[100, 101, 102],
                       [103, 104, 105],
                       [106, 107, 108]]]]])

print(five_d)



[[[[[  1   2   3]
    [  4   5   6]
    [  7   8   9]]

   [[ 10  11  12]
    [ 13  14  15]
    [ 16  17  18]]

   [[ 19  20  21]
    [ 22  23  24]
    [ 25  26  27]]]


  [[[ 28  29  30]
    [ 31  32  33]
    [ 34  35  36]]

   [[ 37  38  39]
    [ 40  41  42]
    [ 43  44  45]]

   [[ 46  47  48]
    [ 49  50  51]
    [ 52  53  54]]]]



 [[[[ 55  56  57]
    [ 58  59  60]
    [ 61  62  63]]

   [[ 64  65  66]
    [ 67  68  69]
    [ 70  71  72]]

   [[ 73  74  75]
    [ 76  77  78]
    [ 79  80  81]]]


  [[[ 82  83  84]
    [ 85  86  87]
    [ 88  89  90]]

   [[ 91  92  93]
    [ 94  95  96]
    [ 97  98  99]]

   [[100 101 102]
    [103 104 105]
    [106 107 108]]]]]


In [12]:
np.ndim(five_d)

5